### ISSUE TITLE
The generator cannot reflect any changes

### ISSUE THREAD

**Issue by ibllex** [tsparticles/website#20]
I tried to make some changes based on the preset below. But no matter what I change in the form on the left, it doesn't show up in the preview.

I tried clicking the Reload button but it doesn't work.

https://particles.js.org/samples/#parallax

Please advise.

**Comment by matteobruni** [comment]
Fixed in https://github.com/tsparticles/website/commit/b19176d12ea332ffa42f8942e29e0930663b1a23
